---
redis-cluster:
  enabled: false
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: false

gitea:
  admin:
    existingSecret: gitea-admin-secret
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
    server:
      domain: &fqdn "gitea.your.domain"

service:
  ssh:
    type: LoadBalancer
    port: 22
    externalTrafficPolicy: Cluster
    annotations:
      metallb.universe.tf/allow-shared-ip: nginx-gitea-share
      metallb.universe.tf/address-pool: v4-pool

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  hosts:
  - host: *fqdn
    paths:
      - path: /
        pathType: Prefix
  tls:
  - hosts:
    - *fqdn
    secretName: gitea-tls
