---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: v4-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.60.51-192.168.60.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: v4-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - v4-pool
  interfaces:
    - eth0
